-- Update admin user password hash
-- Password: admin123
-- Hash generated by backend BCrypt encoder

UPDATE users 
SET password_hash = '$2a$10$0p1J.ri8kf75ooffxhAK1FuK0p/.cGzqqgh0XDDarCfdWIoRwUWxc2'
WHERE username = 'simmonscs28@gmail.com';
