name: Terraform Apply

on:
  push:
    branches: [main]
    paths: ['terraform/**']
  workflow_dispatch:

env:
  TF_VERSION: 1.6.2
  AWS_REGION: us-east-1

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform/environments/dev

      - name: Output Infrastructure Info
        run: terraform output -json > infrastructure-outputs.json
        working-directory: ./terraform/environments/dev

      - name: Upload Outputs
        uses: actions/upload-artifact@v4
        with:
          name: infrastructure-outputs
          path: ./terraform/environments/dev/infrastructure-outputs.json
