name: Terraform Plan

on:
  pull_request:
    branches: [main]
    paths: ['terraform/**']

env:
  TF_VERSION: 1.6.2
  AWS_REGION: us-east-1

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ./terraform

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform/environments/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform/environments/dev

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ./terraform/environments/dev

      - name: Comment PR
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');
            
            try {
              const plan = execSync('terraform plan -no-color', {
                cwd: './terraform/environments/dev',
                encoding: 'utf8'
              });
              
              const comment = `## Terraform Plan - Dev Environment
              
              \`\`\`
              ${plan}
              \`\`\`
              `;
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment
              });
            } catch (error) {
              console.error('Error generating plan comment:', error);
            }
